namespace pseudoCPU.Core;

public enum BootstrapOpcode : byte
{
    BitZeroPage = 0x24,
    Clc = 0x18,
    Php = 0x08,
    Plp = 0x28,
    Pha = 0x48,
    Pla = 0x68,
    AslAccumulator = 0x0A,
    Sec = 0x38,
    Cli = 0x58,
    Sei = 0x78,
    LsrAccumulator = 0x4A,
    RolAccumulator = 0x2A,
    JsrAbsolute = 0x20,
    Rts = 0x60,
    RorAccumulator = 0x6A,
    LdaImmediate = 0xA9,
    AdcImmediate = 0x69,
    LdyImmediate = 0xA0,
    LdxImmediate = 0xA2,
    CpyImmediate = 0xC0,
    Iny = 0xC8,
    Dey = 0x88,
    Tax = 0xAA,
    Inx = 0xE8,
    Dex = 0xCA,
    StaAbsolute = 0x8D,
    StyAbsolute = 0x8C,
    StxAbsolute = 0x8E,
    CmpImmediate = 0xC9,
    CpxImmediate = 0xE0,
    JmpAbsolute = 0x4C,
    BeqRelative = 0xF0,
    BneRelative = 0xD0,
    SbcImmediate = 0xE9,
    Cld = 0xD8,
    Clv = 0xB8,
    Sed = 0xF8,
    Brk = 0x00,
}

public static class BootstrapOpcodeDecoder
{
    public static BootstrapOpcode Decode(byte opcode) => opcode switch
    {
        0x18 => BootstrapOpcode.Clc,
        0x24 => BootstrapOpcode.BitZeroPage,
        0x08 => BootstrapOpcode.Php,
        0x28 => BootstrapOpcode.Plp,
        0x48 => BootstrapOpcode.Pha,
        0x68 => BootstrapOpcode.Pla,
        0x0A => BootstrapOpcode.AslAccumulator,
        0x38 => BootstrapOpcode.Sec,
        0x58 => BootstrapOpcode.Cli,
        0x78 => BootstrapOpcode.Sei,
        0x4A => BootstrapOpcode.LsrAccumulator,
        0x2A => BootstrapOpcode.RolAccumulator,
        0x20 => BootstrapOpcode.JsrAbsolute,
        0x60 => BootstrapOpcode.Rts,
        0x6A => BootstrapOpcode.RorAccumulator,
        0xA9 => BootstrapOpcode.LdaImmediate,
        0x69 => BootstrapOpcode.AdcImmediate,
        0xA0 => BootstrapOpcode.LdyImmediate,
        0xA2 => BootstrapOpcode.LdxImmediate,
        0xC0 => BootstrapOpcode.CpyImmediate,
        0xC8 => BootstrapOpcode.Iny,
        0x88 => BootstrapOpcode.Dey,
        0xAA => BootstrapOpcode.Tax,
        0xE8 => BootstrapOpcode.Inx,
        0xCA => BootstrapOpcode.Dex,
        0x8D => BootstrapOpcode.StaAbsolute,
        0x8C => BootstrapOpcode.StyAbsolute,
        0x8E => BootstrapOpcode.StxAbsolute,
        0xC9 => BootstrapOpcode.CmpImmediate,
        0xE0 => BootstrapOpcode.CpxImmediate,
        0x4C => BootstrapOpcode.JmpAbsolute,
        0xF0 => BootstrapOpcode.BeqRelative,
        0xD0 => BootstrapOpcode.BneRelative,
        0xE9 => BootstrapOpcode.SbcImmediate,
        0xD8 => BootstrapOpcode.Cld,
        0xB8 => BootstrapOpcode.Clv,
        0xF8 => BootstrapOpcode.Sed,
        0x00 => BootstrapOpcode.Brk,
        _ => throw new NotSupportedException($"Unsupported bootstrap opcode '0x{opcode:X2}'."),
    };
}
